replicaCount: 1

db:
  name: db
  namespace: database-helm
  container:
    image: postgres:10.15-alpine
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: kanban-data
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
  pvc:
    name: kanban-data-pvc
    accessMode: ReadWriteOnce
    storage: 1Gi
  config:
    name: db-config
    data:
    - key: key
      value: value
#  secret:
#   name: secret
#    user:
#      key: key
#      value: value
#    password:
#     key: key
#      value: value